### ISSUE TITLE
gh: cannot execute binary file Error: Process completed with exit code 126.

### ISSUE THREAD

**Issue by ax-jli** [dev-hanz-ops/install-gh-cli-action#7]
This is Mac. I think gh cli installed but missing `+x`?

**Comment by dev-hanz-ops** [comment]
This action is a super simple one that is hardcoded to use the linux amd64 release:

https://github.com/dev-hanz-ops/install-gh-cli-action/blob/44745680363a7ba976f907c6d1b697a9fc311cf7/src/run.js#L29

You are welcome to raise a PR that introduces Mac support, in a similar fashion to https://github.com/ksivamuthu/actions-setup-gh-cli/blob/52a7c6659db375e08e92b1bd0ff31be356f574f8/src/main.ts#L29 and https://github.com/sersoft-gmbh/setup-gh-cli-action/blob/2bbde2a400d1fac05bd2d2edd396a61c5b75157c/src/main.ts#L221 - or simply use one of those actions directly. They don't `chmod` too, though.
